### ISSUE TITLE
Update headers to 1.1.91 for supporting final NV raytracing ext..

### ISSUE THREAD

**Issue by oscarbg** [zeux/volk#14]
Hi,
new Windows 416.81 and Linux 415.13 drivers only support final NV_ray_tracing extension..
seems to be present on >=1.1.91 headers..

**Comment by zeux** [comment]
I am waiting for official release of Vulkan SDK to do that

**Comment by oscarbg** [comment]
thanks!

**Comment by iOrange** [comment]
Had to manually fix that in volk as I'm using it to load Vulkan functions

**Comment by zeux** [comment]
I was hoping that the new Vulkan SDK will be released soon after the new drivers but it doesn't look like that. @iOrange I'm assuming you're using Vulkan-Headers instead of the official Vulkan SDK to get the new structures?

**Comment by iOrange** [comment]
Yes. It's a weird situation, where Nvidia deprecated and dropped the support for NVX, and we don't have an SDK with the new stuff. So I have to use up-to-date Vulkan Headers from github + manually built tools and compilers.

BTW - thanks for the Volk library! It's awesome!

**Comment by zeux** [comment]
Yeah... Basically I wanted to delay the update because I know some people used volk with NVX extensions for RTX, and updating volk would break that, but of course now with updated drivers you need new extensions.

What I'm going to do is that I'm going to update to new version of the spec, *but* I will leave support for NVX for now (by manually restoring that). When new SDK goes live I'll be able to just regenerate the bindings and NVX stuff will disappear.

**Comment by iOrange** [comment]
Thanks a lot! That'll help us. 🙇‍♂️

**Comment by zeux** [comment]
Just submitted an update; I've checked that it seems to work with Vulkan SDK 1.1.85, and compiles with new Vulkan-Headers so in theory it should be good. It exposes NVX or NV extension based on whether the Vulkan headers in PATH expose one or the other so should "just work"... hopefully :)
