### ISSUE TITLE
Access violation in volkInitialize

### ISSUE THREAD

**Issue by benreid24** [zeux/volk#150]
I am running into a similar issue to #58 and am getting a write access violation in the same location. Weirdly, however, the violation only occurs when I remove code from a virtual method. The code being removed is not executed prior to the access violation. (Example commit of what I mean: https://github.com/benreid24/BLIB/commit/30468394ee63516f9dccd68d0b71b5637a68f8f3).

<img width="718" alt="volk" src="https://github.com/zeux/volk/assets/19213335/b88f473c-0004-426c-8420-838101966d0a">
<img width="923" alt="mem" src="https://github.com/zeux/volk/assets/19213335/3c74a5ef-ce47-4b3c-b489-748688dfd395">

It appears that somehow the `vkGetInstanceProcAddr` variable is getting placed in readonly (or otherwise protected) memory. In the screenshot you can see that it has a non-null value prior to the assignment, and it's the assignment itself that is failing. I don't know how that could be corrupted at runtime because it's a direct access to a global variable. I am running Windows 10 with an Nvidia 1080 and using Visual Studio (MSVC) to build and run. Verified that the same issue also happens on a different machine (similar specs but different Nvidia GPU).

I unfortunately do not have a minimal reproducible example, but the error should be reproducible by running this example: https://github.com/benreid24/BLIB/blob/volk-working/examples/Graphics/main.cpp. The `volk-broken` and `volk-working` branches illustrate the error. To build after cloning:
- `git submodule update --init --recursive`
- `cmake -S . -B ./build` (use your generator of choice)
- `cmake --build ./build --target graphics`

**Comment by zeux** [comment]
Something like this can happen due to symbol conflicts if your final executable includes a dependency on libvulkan1.dll (which is both redundant and prohibited when volk is used). It's possible that the presence or absence of some code in your executable causes a change in linking order somehow which makes this issue dependent on seemingly unrelated code. The libvulkan1.dll dependency could come directly from CMake settings or possibly from a dependency?

I would also recommend updating to latest volk; I think you're using 1.3.256, and there was a possibly related issue in volk's own CMakeLists.txt that could manifest depending on the configuration, which was fixed in https://github.com/zeux/volk/commit/3f3e0cbbc16c61f940281d29dde5cb9cc02630bb

**Comment by benreid24** [comment]
Good call! I updated to the latest volk and the issue stopped. Thanks for the help!
