### ISSUE TITLE
Tagging for versions since 1.3.270

### ISSUE THREAD

**Issue by rudolfkastl** [zeux/volk#160]
Could you please add tags to the codebase when a new release of vulkan is handled? The last tag is 1.3.270 but the repo has updates for 272 and 273. Tagging makes it more straightforward to package the correct checkout version for distributions.

Thank you!

**Comment by zeux** [comment]
I'm not sure I like this idea. The update flow for volk is currently fully automated and is relying on PRs that are auto-merged. This works well because it runs action checks, restricts the permissions in a reasonable way and provides email notifications for repository watchers. My understanding is that to update tags automatically I'd need to completely bypass the PR process for the updates. Additionally, currently regular 1.3.x tags correspond to releases that have release summaries; it requires manual effort to summarize the updates so it's not something that happens frequently.

I would probably recommend using `vulkan-sdk-1.3.x` tags for distribution; these correspond to Vulkan SDK releases and should be generally speaking consistent across ecosystem (e.g. if you're packaging glslang, you can package from https://github.com/KhronosGroup/glslang/tree/vulkan-sdk-1.3.268.0 tag as well - it will not have any tagging or commits for versions like 272/273). I think the cadence of Vulkan SDK releases is a few months, to get a sense of the number of tags you'll see change with this process.

The only alternative would be to somehow change automatic flow to incorporate tag updates, and come up with some other way of handling GitHub releases. Not sure that's worthwhile.
