### ISSUE TITLE
Tags for versions >1.3.283.0

### ISSUE THREAD

**Issue by fgaz** [zeux/volk#191]
There are no tags for versions after 1.3.283.0, just commits. Could you add them?

**Comment by zeux** [comment]
There are no tags for later versions because there hasn't been a more recent Vulkan SDK release yet.

The tagging strategy for this repository is:

1. Every Vulkan SDK release there's a vulkan-sdk-$version tag (earlier versions used sdk-$version)
2. There's occasionally a GitHub release that has an associated "1.x.y" tag. These are not done for every Vulkan version upgrade. I was waiting for 1.3.290 to make one because I'm trying to do them once every ~20 updates.

**Comment by zeux** [comment]
(if 1.3.289 helps I could release that today instead, as the "20 update gap" is just arbitrary to manage manual work associated with tags/releases)

**Comment by fgaz** [comment]
Oh, I see. Looks like I misunderstood the vulkan-sdk _and_ volk tagging strategies, thank you for explaining.

Yes, a 1.3.289 tag would be helpful, thank you!

**Comment by fgaz** [comment]
Nevermind, turns our I can do just fine without. Sorry for the noise!
